Django project/blog/urls.py
from django.urls import path
from . import views

app_name = 'bloging'

urlpatterns = [
    path("", views.index, name= "index"),
    path("detail/<str:post_id>", views.detail, name='detail')
    
]



Django project/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 ='myapp.views.custom404Error'

urlpatterns = [
    path("blog/", include('blog.urls')),
    path('admin/', admin.site.urls),
    
]

Django project/blog/models.py
from django.db import models
import logging
# Create your models here.
class post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title







Django project/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
import logging
from blog.models import post
# appName = [
#         {'id':1, 'names': 'post1', 'content': 'viewing post one'},
#         {'id':2, 'names': 'post2', 'content': 'viewing post two'},
#         {'id':3,'names': 'post3', 'content': 'viewing post three'},
#         {'id':4, 'names': 'post4', 'content': 'viewing post four'},
        
#     ]

# Create your views here.
def index(request):
    appName = post.objects.all()
    return render(request, 'index.html', {"postItem": appName})

def detail(request, post_id):
    items = post.objects.get(pk=post_id)
    # items = next((item for item in appName if item['id'] == int(post_id)), "None")
    return render(request, 'detail.html', {'posts': items})


Django project/myapp/views.py
from django.shortcuts import render

def custom404Error(request, exception):
    return render(request, '404.html', status=404)

Django project/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h1>this text from base content</h1>
       {% block content %}
       {% endblock %}
    </div>
</body>
</html>

Django project/blog/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../../../../my installer/bootstrap-3.4.1-dist/css/bootstrap.min.css">
    
    
</head>
<body >
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
               <a class="text-decoration-none text-light" href="./index.html"><h3>Blog</h3></a> 
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="">Home</a>
                    <a class="text-light text-decoration-none" href="">About</a>
                    <a class="text-light text-decoration-none" href="">Contact</a>
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{posts.title}} {{posts.id}}</h1>
              <p class="text-muted">Posted on January 1, 2024</p>
              <img src="https://via.placeholder.com/800x400" class="img-fluid mb-4" alt="Blog Image">
              <p>{{posts.content}}</p>
             
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    <li><a href="./detail.html">Post 1</a></li>
                    <li><a href="./detail.html">Post 2</a></li>
                    <li><a href="./detail.html">Post 3</a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
    <footer class="bg-dark text-light p-3 fixed-bottom">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>
    <script src="../../../../my installer/bootstrap-3.4.1-dist/js/jquery.min.js"></script>
</body>
</html>

Django project/blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../../../../my installer/bootstrap-3.4.1-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./style.css">
</head>
<body >
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h3>Blog</h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="">Home</a>
                    <a class="text-light text-decoration-none" href="">About</a>
                    <a class="text-light text-decoration-none" href="">Contact</a>
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid ">
        
        <div class="row">
            <h2 >Latest Posts</h2>
        </div>
        {% for post in postItem %}
        <div class="row m-3">
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="https://via.placeholder.com/300" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'bloging:detail' post_id=post.id %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">Sports</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        <div class="row">
           
        </div>
        
    </div>
    <footer class="bg-dark text-light p-3 fixed-bottom">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>
   <script src="../../../../my installer/bootstrap-3.4.1-dist/js/jquery.min.js"></script>
</body>
</html>